using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Segurplan.Core.Actions.Plans.PlanManagement.DefaultValues;
using Segurplan.Core.BusinessObjects;
using Segurplan.Core.Database;
using Segurplan.DataAccessLayer.Database.DataTransferObjects;

namespace Segurplan.Migrations.SqlServer.Seeds {
    public class PlanDetailsDefaultValuesSeed : IDataSeed {

        public List<PlanDetailsDefaultValues> PlanDetailsDefaultValues = new List<PlanDetailsDefaultValues> {
            new PlanDetailsDefaultValues{
                PropName=DefaultValuePropNameList.AffectedServicesTrue.ToString(),
                Content="<p class=\"MsoNormal\" style=\"margin-bottom:0cm;text-align:justify;line-height:normal;" +
                "mso-layout-grid-align:none;text-autospace:none;  font-size:9pt;font-family:Verdana, sans-serif;\">" +
                "De acuerdo con lo previsto en el proyecto, las interferencias y servicios afectados son" +
                "</p>"
            },
            new PlanDetailsDefaultValues{
                PropName=DefaultValuePropNameList.AffectedServicesFalse.ToString(),
                Content="<p class=\"MsoNormal\" style=\"text-align:justify; font-size:9pt;font-family:Verdana, sans-serif;\">Los trabajos se desarrollarán en el emplazamiento de la " +
                "obra destinado a tal fin, y cuyo destino es exclusivamente la ubicación de las instalaciones objetos del proyecto, por lo que las únicas " +
                "interferencias que pueden presentarse son las superposiciones de las diversas fases de los trabajos. <br>Si durante el desarrollo de los " +
                "trabajos, se detectara algún servicio afectadono identificado inicialmente, se analizará y se tomarán las medidas necesarias para el desarrollo " +
                "seguro de los trabajos.</p><br>"
            },
            new PlanDetailsDefaultValues{
                PropName=DefaultValuePropNameList.IdEmergencyPlanTypeCorto.ToString(),
                Content="<p class=\"MsoNormal\" align=\"center\" style=\"margin-bottom:0cm; text-align:center;line-height:normal;font-size:10pt;font-family:Verdana, sans-serif\"><b><u>PLAN DE EMERGENCIA:</u></b></p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif\">"
                        +"Los trabajadores conocerán desde el primer día los recorridos de evacuación, las posibles salidas de emergencia, situación de los elementos de lucha contra el fuego, ubicación del botiquín de primeros auxilios, etc. En caso de accidente, se debe actuar de acuerdo al protocolo <b>PAS:</b>"
                        +"</p><br>"
                        +"<div style=\"padding:1.0pt 4.0pt 1.0pt 4.0pt;margin-left:18.0pt;margin-right:-1.4pt\">"
                            +"<p class=\"MsoNormal\" align=\"center\" style=\"margin-top:6.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:center;line-height:normal;border:none;padding:0cm;font-size:10pt;line-height:normal;font-family:Verdana, sans-serif\"> <u>PROTEGER - AVISAR- SOCORRER(PAS)"
                            +"</u></p><br><br>"
                            +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0cm;font-size:9pt;font-family:Verdana, sans-serif\">· <b>PROTEGE</b>, al accidentado y a ti como auxiliador, no incurriendo en riesgos innecesarios y pensando antes de actuar (por ejemplo, no tocaremos directamente a un electrocutado, debiendo cortar la fuente de alimentación de energía si es posible, o retirando al accidentado con algún elemento aislante)."
                            +"</p><br>"
                            +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0cm;font-size:9pt;font-family:Verdana, sans-serif\">· <b>AVISA</b>, si las características del accidente lo hace necesario, a los Servicios de Urgencia de la existencia del accidente, dando los datos del lugar exacto donde ha ocurrido y la gravedad / características del accidente."
                            +"</p><br>"
                            +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0cm;font-size:9pt;font-family:Verdana, sans-serif\">· <b>SOCORRE</b> al accidentado, a la espera de la llegada de los Servicios de Urgencia, o evacuando al accidentado si las características de las lesiones lo permiten (en caso de sospechar la existencia de lesiones graves, NO MOVER al accidentado para no agravar las lesiones sufridas, salvo que sea absolutamente necesario por la situación de peligro que pueda existir)."
                        +"</p></div><br><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">"
                        +"Para la realización de los posibles primeros auxilios, en la obra existirá personal que haya recibido formación en Primeros Auxilios, disponiendo en obra o en los vehículos de un botiquín que permita la realización de los mismos. En caso de producirse un accidente que haga necesario el traslado del accidentado al Centro Asistencial más próximo, el traslado se realizará en el vehículo de obra, o si las lesiones sufridas lo hacen desaconsejable, se avisará a los Servicios de Emergencia para que procedan a su evacuación. Se debe facilitar la evacuación y la comunicación de emergencias, en un lugar visible de la obra, cada Contratista colocará un cartel donde se indiquen los teléfonos y direcciones de emergencias y centros asistenciales, en los que se pondrán como mínimo los siguientes:"
                        +"</p><br><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:130%;page-break-after:avoid;font-size:9pt;font-family:Verdana, sans-serif;\"><b><u>TELÉFONOS SERVICIOS DE URGENCIA:</u></b></p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">EMERGENCIAS: 112</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">BOMBEROS: 080</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">POLICÍA NACIONAL: 091</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">POLICÍA LOCAL: 092</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">PROTECCIÓN CIVIL: 112 24H</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">MUTUA ASEPEYO: 900 151 000</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">DE ATENCIÓN AL USUARIO ASEPEYO: 902 151 002</p><br><br><br>"
                        +"<p class=\"MsoNormal\" style=\"text-align:justify;font-size:9pt;font-family:Verdana, sans-serif;\"><b><u>DIRECCIONES Y TELÉFONOS DE CENTROS ASISTENCIALES:</u></b></p><br>"
            },
            new PlanDetailsDefaultValues{
                PropName=DefaultValuePropNameList.IdEmergencyPlanTypeMediano.ToString(),
                Content="<p class=\"MsoNormal\" align=\"center\" style=\"margin-bottom:0px; text-align:center;line-height:normal;font-size:10pt;font-family:Verdana, sans-serif\"><b><u>PLAN DE EMERGENCIA:</u></b></p><br>"
+"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif\">"
+"Los trabajadores conocerán desde el primer día los recorridos de evacuación, las posibles salidas de emergencia, situación de los elementos de lucha contra el fuego, ubicación del botiquín de primeros auxilios, etc. En caso de accidente, se debe actuar de acuerdo al protocolo <b>PAS:</b>"
+"</p><br><br>"
+"<div style=\"padding:1.0pt 4.0pt 1.0pt 4.0pt;margin-left:18.0pt;margin-right:-1.4pt\">"
+"<p class=\"MsoNormal\" align=\"center\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:0px;text-align:center;line-height:normal;border:none;padding:0px;font-size:10pt;line-height:normal;font-family:Verdana, sans-serif\"> <u>PROTEGER - AVISAR- SOCORRER(PAS)"
+"</u></p><br><br>"
+"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0px;font-size:9pt;font-family:Verdana, sans-serif\">· <b>PROTEGE</b>, al accidentado y a ti como auxiliador, no incurriendo en riesgos innecesarios y pensando antes de actuar (por ejemplo, no tocaremos directamente a un electrocutado, debiendo cortar la fuente de alimentación de energía si es posible, o retirando al accidentado con algún elemento aislante)."
+" </p><br>"
+" <p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0px;font-size:9pt;font-family:Verdana, sans-serif\">· <b>AVISA</b>, si las características del accidente lo hace necesario, a los Servicios de Urgencia de la existencia del accidente, dando los datos del lugar exacto donde ha ocurrido y la gravedad / características del accidente."
+" </p><br>"
+"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0px;font-size:9pt;font-family:Verdana, sans-serif\">· <b>SOCORRE</b> al accidentado, a la espera de la llegada de los Servicios de Urgencia, o evacuando al accidentado si las características de las lesiones lo permiten (en caso de sospechar la existencia de lesiones graves, NO MOVER al accidentado para no agravar las lesiones sufridas, salvo que sea absolutamente necesario por la situación de peligro que pueda existir)."
+"</p></div><br><br>"
+"</p></div><br><br>"
+"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">"
    +"Para la realización de los posibles primeros auxilios, en la obra existirá personal que haya recibido formación en Primeros Auxilios, disponiendo en obra o en los vehículos de un botiquín que permita la realización de los mismos. Encaso de producirse un accidente que haga necesario el traslado del accidentado al Centro Asistencial más próximo, el traslado se realizará en el vehículo de obra, o si las lesiones sufridas lo hacen desaconsejable, se avisará a los Servicios de Emergencia para que procedan a su evacuación."
    +"</p><br><br>"
    +"<p class=\"MsoNormal\" align=\"center\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:0px;text-align:center;line-height:normal;border:none;padding:0px;font-size:10pt;line-height:normal;font-family:Verdana, sans-serif\"> <u>Actuaciones ante situaciones de emergencia:"
        +"</u></p><br><br>"
        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-family:Verdana, sans-serif;font-size:9pt\">"
        +"A) INCENDIO: en caso de producirse un <b>incendio,</b> todos los trabajadores colaboraran en la medida de sus conocimientos y posibilidades, comunicando inmediatamente que se ha producido un incendio interna y externamente, si por las dimensiones del mismo es necesario. Para evitar o minimizar un incendio, se dispondrán y mantendrán en buen estado los equipos de detección y lucha contra incendios necesarios. Una vez comunicado el incendio, se iniciara la lucha contra el mismo, actuando en función del tamaño del fuego y no arriesgando innecesariamente. Si por las dimensiones del mismo comprobáramos que no se va a poder sofocar, abandonar el lugar de forma rápida y ordenada. En el caso de incendios en presencia de instalaciones eléctricas, se procurará desconectar la alimentación eléctrica antes de iniciar las tareas de extinción. Se debe utilizar el tipo de extintores más adecuado al tipo de fuego a sofocar, según el siguiente cuadro:"
        +"</p><br><br>"
        +"<div align=\"center\">"
        +"<p style=\"font-size:10pt;font-family:Verdana, sans-serif\"><b>EFICACIA DE AGENTE EXTINTOR RESPECTO A LA CLASE DE FUEGO</b></p><br><br>"
        +" <table class=\"table table-bordered\" style=\"border:1px solid black\">"
        +"<tbody>"
        +" <tr style=\"border:1px solid black\">"
        +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"><b>TIPO DE FUEGO<br></b>"
        +" </td>"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"><b>RECOMENDADO<br></b>"
        +" </td>"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"><b> NO RECOMENDADO</b><br>"
        +" </td>"
        +"</tr>"
        +" <tr style=\"border:1px solid black\">"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"> A - SÓLIDOS<br></td>"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"> AGUA - POLVO POLIVALENTE<br></td>"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"> POLVO SECO<br></td>"
        +" </tr>"
        +" <tr style=\"border:1px solid black\">"
        +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">B - LIQUIDOS<br></td>"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"> POLVO POLIVALENTE<br>"
        +"</td>"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">AGUA<br></td>"
        +" </tr>"
        +"<tr style=\"border:1px solid black\">"
        +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">C - GASES <br></td>"
        +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">POLVO POLIVALENTE<br>"
        +"</td>"
        +"  <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">AGUA<br></td>"
        +"</tr>"
        +"<tr style=\"border:1px solid black\">"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">D-METALES<br></td>"
        +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">POLVO ESPECÍFICO METALES<br></td>"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">AGUA<br></td>"
        +" </tr>"
        +" <tr style=\"border:1px solid black\">"
        +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">E-ELÉCTRICOS<br></td>"
        +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">CO-HALÓN<br></td>"
        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">AGUA<br></td>"
        +" </tr>"
        +" </tbody>"
        +"</table>"
        +"</div>"

        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-family:Verdana, sans-serif;font-size: 9pt;\">"
            +"B) CONTACTOS ELÉCTRICOS: En caso de producirse<b> un contacto eléctrico de una máquina/grúa con una línea eléctrica aérea</b>, se tendrán en cuenta las siguientes pautas de actuación: </p><br><br>"
            +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                +"<span style=\"font-size: 9pt;font-family:Symbol;\">·"
                    +"</span>"
                        +" El conductor de la maquinaria estará adiestrado para conservar la calma incluso si los neumáticos comienzan a arder. No abandonará su puesto de mando o la cabina, debido a que allí está libre del riesgo de electrocución.</p><br><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px; margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                            +" <span style=\"font-size: 9pt;font-family:Symbol;\">·"
                                +"</span>"
                                    +" Se intentará retirar la máquina de la línea (bajando el basculante, el brazo de la grúa, etc.) y situarla fuera de la zona peligrosa.</p><br><br>"
                                    +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px; margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                                        +"<span style=\"font-size: 9pt;font-family:Symbol\">·</span>"
                                        +" Advertirá a las personas que se encuentren en las inmediaciones de que no deben tocar la máquina.</p><br><br>"
                                        +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px;  margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                                            +"<span style=\"font-size: 9pt;font-family:Symbol;\">·</span>"
                                                +" No descenderá de la máquina hasta que ésta no se encuentre a una distancia segura. Si se desciende antes, el conductor estará en el circuito eléctrico línea - máquina - suelo y seriamente expuesto a electrocutarse.</p><br><br>"
                                                +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px;   margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                                                    +"<span style=\"font-size: 9pt;font-family:Symbol;\">·</span>"
                                                        +" Si no es posible separar la máquina y en caso de absoluta necesidad, el conductor o maquinista no descenderá utilizando los medios habituales, sino que saltará lo más lejos posible de la máquina, evitando tocar ésta.</p><br><br>"
                                                        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom: 0px;margin-left:0px;text-align:justify;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif\">"
                                                            +"En caso de<b> contacto eléctrico de una persona</b>, no se tocará directamente al accidentado, desconectándose a la mayor brevedad posible la alimentación, o retirando a la persona con la ayuda de un elemento aislante adecuado al nivel de tensión de la instalación. Una vez retirado de la zona de peligro, se iniciaran las labores de primeros auxilios.</p><br><br>"
                                                            +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif\">"
                                                                +"C) ESPACIOS CONFINADOS: en caso de producirse<b> un accidente en un espacio confinado</b>, relacionado con la eventual presencia de una atmósfera peligrosa, <b><u>no</u></b> se accederá al interior del mismo sin previamente avisar a los equipos de emergencia y disponer de la formación y los equipos de rescate mínimos adecuados, como pueden ser equipos de respiración autónoma, medios auxiliares de evacuación y emergencias, etc.</p><br><br>"
                                                                +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                                                                    +"Facilitar la evacuación y la comunicación de emergencias, en un lugar visible de la obra cada Contratista colocará un cartel donde se indiquen los teléfonos y direcciones de emergencias y centros asistenciales, en los que se pondrán como mínimo los siguientes:</p><br><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:130%;page-break-after:avoid;font-size:9pt;font-family:Verdana, sans-serif;\"><b><u>TELÉFONOS SERVICIOS DE URGENCIA:</u></b></p><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">EMERGENCIAS: 112</p><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">BOMBEROS: 080</p><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">POLICÍA NACIONAL: 091</p><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">POLICÍA LOCAL: 092</p><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">PROTECCIÓN CIVIL: 112 24H</p><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">MUTUA ASEPEYO: 900 151 000</p><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">DE ATENCIÓN AL USUARIO ASEPEYO: 902 151 002</p><br><br><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"text-align:justify;font-size:9pt;font-family:Verdana, sans-serif;\"><b><u>DIRECCIONES Y TELÉFONOS DE CENTROS ASISTENCIALES:</u></b></p><br>"
            },
            new PlanDetailsDefaultValues{
                PropName=DefaultValuePropNameList.IdEmergencyPlanTypeLargo.ToString(),
                Content="<p class=\"MsoNormal\" align=\"center\" style=\"margin-bottom:0px; text-align:center;line-height:normal;font-size:10pt;font-family:Verdana, sans-serif\"><b><u>PLAN DE EMERGENCIA:</u></b></p><br>"
+"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif\">"
    +"Los trabajadores conocerán desde el primer día los recorridos de evacuación, las posibles salidas de emergencia, situación de los elementos de lucha contra el fuego, ubicación del botiquín de primeros auxilios, etc. Se trasmitirán las indicaciones y medidas preventivas previstas en el Plan de Autoprotección de la instalación a todos los trabajadores, para su conocimiento y aplicación, incorporando si así está previsto a personal de la empresa a los equipos de intervención de la instalación. Se mantendrá actualizada la información trasmitida a los trabajadores en caso de modificaciones de vías de emergencia, ubicación de extintores, etc., a lo largo del desarrollo del proyecto."
    +"</p><br><br>"
    +"<p style=\"font-size: 10pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">"
        +"AREA DE ESCRITURA LIBRE: Señalización de puntos S.O.S.; Acogerse al Plan de autoprotección del Promotor; Ejecución de un Plan de Prevención de Incendios especifico; Pautas de trabajo en Atmósfera ATEX; </p><br>"
        +"<p style=\"font-size: 9pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif\">En caso de accidente, se debe actuar de acuerdo al protocolo<b> PAS:</b></p><br>"
+"<div style=\"padding:1.0pt 4.0pt 1.0pt 4.0pt;margin-left:18.0pt;margin-right:-1.4pt\">"
    +"<p class=\"MsoNormal\" align=\"center\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:0px;text-align:center;line-height:normal;border:none;padding:0px;font-size:10pt;line-height:normal;font-family:Verdana, sans-serif\"> <u>PROTEGER - AVISAR- SOCORRER(PAS)"
        +"</u></p><br>"
        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0px;font-size:9pt;font-family:Verdana, sans-serif\">· <b>PROTEGE</b>, al accidentado y a ti como auxiliador, no incurriendo en riesgos innecesarios y pensando antes de actuar (por ejemplo, no tocaremos directamente a un electrocutado, debiendo cortar la fuente de alimentación de energía si es posible, o retirando al accidentado con algún elemento aislante)."
            +"</p><br>"
            +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0px;font-size:9pt;font-family:Verdana, sans-serif\">· <b>AVISA</b>, si las características del accidente lo hace necesario, a los Servicios de Urgencia de la existencia del accidente, dando los datos del lugar exacto donde ha ocurrido y la gravedad / características del accidente."
                +"</p><br>"
                +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:18.0pt;text-align:justify;text-indent:-18.0pt;line-height:normal;border:none;padding:0px;font-size:9pt;font-family:Verdana, sans-serif\">· <b>SOCORRE</b> al accidentado, a la espera de la llegada de los Servicios de Urgencia, o evacuando al accidentado si las características de las lesiones lo permiten (en caso de sospechar la existencia de lesiones graves, NO MOVER al accidentado para no agravar las lesiones sufridas, salvo que sea absolutamente necesario por la situación de peligro que pueda existir)."
                    +"</p></div><br><br>"
                    +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">"
    +"Para la realización de los posibles primeros auxilios, en la obra existirá personal que haya recibido formación en Primeros Auxilios, disponiendo en obra o en los vehículos de un botiquín que permita la realización de los mismos. Encaso de producirse un accidente que haga necesario el traslado del accidentado al Centro Asistencial más próximo, el traslado se realizará en el vehículo de obra, o si las lesiones sufridas lo hacen desaconsejable, se avisará a los Servicios de Emergencia para que procedan a su evacuación."
    +"</p><br><br><br>"
    +"<p class=\"MsoNormal\" align=\"center\" style=\"margin-top:6.0pt;margin-right:0px;margin-bottom:0px;margin-left:0px;text-align:center;line-height:normal;border:none;padding:0px;font-size:10pt;line-height:normal;font-family:Verdana, sans-serif\"> <u>Actuaciones ante situaciones de emergencia:"
        +"</u></p><br><br>"
        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-family:Verdana, sans-serif;font-size:9pt\">"
            +"A) INCENDIO: en caso de producirse un <b>incendio,</b> todos los trabajadores colaboraran en la medida de sus conocimientos y posibilidades, comunicando inmediatamente que se ha producido un incendio interna y externamente si por las dimensiones del mismo es necesario. Para evitar o minimizar un incendio, se dispondrán y mantendrán en buen estado los equipos de detección y lucha contra incendios necesarios. Una vez comunicado el incendio, se iniciara la lucha contra el mismo, actuando en función del tamaño del fuego y no arriesgando innecesariamente. Si por las dimensiones del mismo comprobáramos que no se va a poder sofocar, abandonar el lugar de forma rápida y ordenada. En el caso de incendios en presencia de instalaciones eléctricas, se procurará desconectar la alimentación eléctrica antes de iniciar las tareas de extinción.Se debe utilizar el tipo de extintores más adecuado al tipo de fuego a sofocar, según el siguiente cuadro:"
            +"</p><br><br>"
            +"<div align=\"center\">"
                +"<p style=\"font-size:10pt;font-family:Verdana, sans-serif\"><b>EFICACIA DE AGENTE EXTINTOR RESPECTO A LA CLASE DE FUEGO</b></p><br><br>"
                +"<table class=\"table table-bordered\" style=\"border:1px solid black\">"
                    +"<tbody>"
                        +"<tr style=\"border:1px solid black\">"
                            +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"><b>TIPO DE FUEGO<br></b>"
                                +"</td>"
                                +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"><b>RECOMENDADO<br></b>"
                                    +"</td>"
                                    +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"><b> NO RECOMENDADO</b><br>"
                                        +" </td>"
                                        +" </tr>"
                                        +" <tr style=\"border:1px solid black\">"
                                            +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"> A - SÓLIDOS<br></td>"
                                            +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"> AGUA - POLVO POLIVALENTE<br></td>"
                                            +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"> POLVO SECO<br></td>"
                                            +" </tr>"
                                            +"<tr style=\"border:1px solid black\">"
                                                +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">B - LIQUIDOS<br></td>"
                                                +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\"> POLVO POLIVALENTE<br>"
                                                    +"</td>"
                                                    +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">AGUA<br></td>"
                                                    +"</tr>"
                                                    +"<tr style=\"border:1px solid black\">"
                                                        +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">C - GASES <br></td>"
                                                        +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">POLVO POLIVALENTE<br>"
                                                            +" </td>"
                                                            +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">AGUA<br></td>"
                                                            +"</tr>"
                                                            +"<tr style=\"border:1px solid black\">"
                                                                +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">D-METALES<br></td>"
                                                                +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">POLVO ESPECÍFICO METALES<br></td>"
                                                                +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">AGUA<br></td>"
                                                                +"</tr>"
                                                                +"<tr style=\"border:1px solid black\">"
                                                                    +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">E-ELÉCTRICOS<br></td>"
                                                                    +" <td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">CO-HALÓN<br></td>"
                                                                    +"<td style=\"border:1px solid black;font-family:Verdana, sans-serif; font-size:9pt\">AGUA<br></td>"
                                                                    +" </tr>"
                                                                    +"</tbody>"
                                                                    +" </table>"
                                                                    +"</div>"
                                                                    +"<br><br>"
                                                                    +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-family:Verdana, sans-serif;font-size: 9pt;\">"
                                                                        +"B) CONTACTOS ELÉCTRICOS:En caso de producirse<b> un contacto eléctrico de una máquina/grúa con una línea eléctrica aérea</b>, se tendrán en cuenta las siguientes pautas de actuación: </p><br><br>"
                                                                        +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                                                                            +"<span style=\"font-size: 9pt;font-family:Symbol;\">·"
                                                                                +"</span>"
                +" El conductor de la maquinaria estará adiestrado para conservar la calma incluso si los neumáticos comienzan a arder. No abandonará su puesto de mando o la cabina, debido a que allí está libre del riesgo de electrocución.</p><br><br>"
                +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px; margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                    +" <span style=\"font-size: 9pt;font-family:Symbol;\">·"
                        +" </span>"
                            +" Se intentará retirar la máquina de la línea(bajando el basculante, el brazo de la grúa, etc.) y situarla fuera de la zona peligrosa.</p><br><br>"
                            +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px; margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                                +"<span style=\"font-size: 9pt;font-family:Symbol\">·</span>"
                                +" Advertirá a las personas que se encuentren en las inmediaciones de que no deben tocar la máquina.</p><br><br>"
                                +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px;  margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                                    +"<span style=\"font-size: 9pt;font-family:Symbol;\">·</span>"
                                        +" No descenderá de la máquina hasta que ésta no se encuentre a una distancia segura.Si se desciende antes, el conductor estará en el circuito eléctrico línea - máquina - suelo y seriamente expuesto a electrocutarse.</p>"
                                        +"<br><br>"
                                        +"<p class=\"MsoNormal\" style=\"margin-top:0px;margin-right:0px;margin-bottom:0px;   margin-left:2.0px;text-align:justify;text-indent:-1.0px;font-size: 9pt;font-family:Verdana, sans-serif;\">"
    +"<span style=\"font-size: 9pt;font-family:Symbol;\">·</span>"
            +" Si no es posible separar la máquina y en caso de absoluta necesidad, el conductor o maquinista no descenderá utilizando los medios habituales, sino que saltará lo más lejos posible de la máquina, evitando tocar ésta.</span></p><br><br>"
            +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom: 0px;margin-left:0px;text-align:justify;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif\">"
                +" En caso de<b> contacto eléctrico de una persona</b>, no se tocará directamente al accidentado, desconectándose a la mayor brevedad posible la alimentación, o retirando a la persona con la ayuda de un elemento aislante adecuado al nivel de tensión de la instalación. Una vez retirado de la zona de peligro, se iniciaran las labores de primeros auxilios.</p><br><br><br>"
                +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif\">"
                    +" C) ESPACIOS CONFINADOS: en caso de producirse<b> un accidente en un espacio confinado</b>, relacionado con la eventual presencia de una atmósfera peligrosa, <b><u>no</u></b> se accederá al interior del mismo sin previamente avisar a los equipos de emergencia y disponer de la formación y los equipos de rescate mínimos adecuados, como pueden ser equipos de respiración autónoma, medios auxiliares de evacuación y emergencias, etc.</p><br><br>"
                    +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:normal;font-size: 9pt;font-family:Verdana, sans-serif;\">"
                        +"Facilitar la evacuación y la comunicación de emergencias, en un lugar visible de la obra cada Contratista colocará un cartel donde se indiquen los teléfonos y direcciones de emergencias y centros asistenciales, en los que se pondrán como mínimo los siguientes:</p><br><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:6.0pt;margin-right:-1.4pt;margin-bottom:0px;margin-left:0px;text-align:justify;line-height:130%;page-break-after:avoid;font-size:9pt;font-family:Verdana, sans-serif;\"><b><u>TELÉFONOS SERVICIOS DE URGENCIA:</u></b></p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">EMERGENCIAS: 112</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">BOMBEROS: 080</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">POLICÍA NACIONAL: 091</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">POLICÍA LOCAL: 092</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">PROTECCIÓN CIVIL: 112 24H</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">MUTUA ASEPEYO: 900 151 000</p><br>"
                        +"<p class=\"MsoNormal\" style=\"margin-top:4.0pt;margin-right:0px;margin-bottom:0px;margin-left:21.3pt;line-height:normal;font-size:9pt;font-family:Verdana, sans-serif;\">DE ATENCIÓN AL USUARIO ASEPEYO: 902 151 002</p><br><br><br>"
                        +"<p class=\"MsoNormal\" style=\"text-align:justify;font-size:9pt;font-family:Verdana, sans-serif;\"><b><u>DIRECCIONES Y TELÉFONOS DE CENTROS ASISTENCIALES:</u></b></p><br>"
            },
        };


        public async Task Seed(SegurplanContext context, CancellationToken cancellationToken = default) {

            context.Database.ExecuteSqlCommand("TRUNCATE TABLE [PlanDetailsDefaultValues]");

            await context.PlanDetailsDefaultValues.AddRangeAsync(PlanDetailsDefaultValues);
            await context.SaveChangesAsync();

        }
    }
}
